### PR TITLE
Fix get command on macOS

### LINKED ISSUE #10: List command sometimes hangs on macOS
Not sure how exactly to reproduce it yet, but the `ls` command periodically hangs on my M1 Air (21.2.0)

### PR DESCRIPTION
**Pull request by kkga**
fixes #10 

Additionally, the `get` command:
- now has an `-R` flag to print out raw Kakoune-quoted output
- prints Kakoune's errors to stderr

### CODE REVIEW

**Comment by kkga** [comment]
@TeddyDD Hey 👋 

I had to make a few changes in order to fix the hanging issues in `kak.Get()` on macOS.

Problem I isolated, in short: the fsnotify doesn't trigger a WRITE event if the file content is empty after update, so I came up with an ugly solution to always prefix Kakoune's echo output with an arbitrary string that gets trimmed later (https://github.com/kkga/kks/pull/11/commits/b2f27e99cf5820d6e8f6abfcf2203846d60bbf05).

I also added a few more enhancements along the way:
- the `get` command now has an `-R` flag to print out Kakoune-quoted output directly
- if Kakoune errors-out, the error is written to stderr https://github.com/kkga/kks/pull/11/commits/f9f5fb459d8acf433c0bdf9df2040c8302010978

If you a have any desire and/or some free time, I'd appreciate if you could briefly test this to make sure all works :) Thanks!

**Comment by TeddyDD** [comment]
Sure!

**Comment by TeddyDD** [comment]
It seems to be working as expected.

**Comment by kkga** [comment]
Awesome, glad it works for you.

I'm gonna test-drive this for a few more days before merging.

Thank you.

**Comment by TeddyDD** [comment]
Okay, I'll be running this branch as well, let you know if something explodes.

**Pull request merged**
